// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // `prisma dev`'s local Postgres also provisions a dedicated shadow
    // database on port 51215 (same host/creds as DATABASE_URL's port
    // 51214) — point migrate at it explicitly. Without this, `migrate dev`
    // tries to manage its own shadow db on the primary connection, which
    // left stale state behind after the P6000 DATABASE_URL switch (see
    // progress-tracker.md) and started failing with "type already exists".
    shadowDatabaseUrl:
      "postgresql://postgres:postgres@localhost:51215/template1?sslmode=disable&connection_limit=10&connect_timeout=0&max_idle_connection_lifetime=0&pool_timeout=0&socket_timeout=0",
  },
});
