import { rumRoute, VITAL_NAMES, type RumSample } from "./shared";
export function parseRumBatch(body: unknown): RumSample[] | null {
  if (
    !body ||
    typeof body !== "object" ||
    !("samples" in body) ||
    !Array.isArray(body.samples) ||
    !body.samples.length ||
    body.samples.length > 20
  )
    return null;
  const parsed: RumSample[] = [];
  for (const value of body.samples) {
    if (!value || typeof value !== "object") return null;
    const s = value as Record<string, unknown>;
    const number = (v: unknown, max = 3600000) =>
      typeof v === "number" && Number.isFinite(v) && v >= 0 && v <= max;
    const token = (v: unknown) =>
      typeof v === "string" && /^[a-zA-Z0-9_-]{1,100}$/.test(v);
    if (
      !token(s.pageId) ||
      !token(s.sampleId) ||
      !Number.isSafeInteger(s.revision) ||
      !number(s.revision, 2147483647) ||
      !VITAL_NAMES.includes(s.name as never) ||
      !number(s.value, s.name === "CLS" ? 100 : 3600000)
    )
      return null;
    if (
      !["vital", "interaction"].includes(String(s.kind)) ||
      !["mobile", "tablet", "desktop"].includes(String(s.device))
    )
      return null;
    if (
      s.kind === "interaction" &&
      (s.name !== "INP" || Number(s.value) <= 200)
    )
      return null;
    if (
      typeof s.route !== "string" ||
      typeof s.pageRoute !== "string" ||
      s.route !== rumRoute(s.route) ||
      s.pageRoute !== rumRoute(s.pageRoute)
    )
      return null;
    // Match only the structural selector format generated by our collector.
    if (
      s.target !== null &&
      (typeof s.target !== "string" ||
        s.target.length > 300 ||
        !/^(unknown|[a-z][a-z0-9-]*(?::nth-of-type\(\d+\))?( > [a-z][a-z0-9-]*(?::nth-of-type\(\d+\))?){0,4})$/.test(
          s.target,
        ))
    )
      return null;
    if (
      s.eventType !== null &&
      ![
        "click",
        "pointerdown",
        "pointerup",
        "keydown",
        "keyup",
        "mousedown",
        "mouseup",
        "touchstart",
        "touchend",
      ].includes(String(s.eventType))
    )
      return null;
    for (const key of ["inputDelay", "processingDuration", "presentationDelay"])
      if (s[key] !== null && !number(s[key])) return null;
    if (
      s.kind === "interaction" &&
      [
        s.inputDelay,
        s.processingDuration,
        s.presentationDelay,
        s.eventType,
        s.target,
      ].some((v) => v === null)
    )
      return null;
    parsed.push({
      kind: s.kind,
      sampleId: s.sampleId,
      pageId: s.pageId,
      revision: s.revision,
      name: s.name,
      value: s.value,
      route: s.route,
      pageRoute: s.pageRoute,
      device: s.device,
      target: s.target,
      eventType: s.eventType,
      inputDelay: s.inputDelay,
      processingDuration: s.processingDuration,
      presentationDelay: s.presentationDelay,
    } as RumSample);
  }
  return parsed;
}
